[package]
name = "zed-leetcode"
version = "0.1.0"
edition = "2024"

[lib]
name = "zed_leetcode"
crate-type = ["cdylib", "rlib"]

[dependencies]
zed_extension_api = "0.1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
